"""questions table

Revision ID: 20e07f586c72
Revises: f01c5f00e589
Create Date: 2021-04-26 19:55:48.034893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20e07f586c72"
down_revision = "f01c5f00e589"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.String(length=256), nullable=True),
        sa.Column("answer_1", sa.String(length=64), nullable=True),
        sa.Column("answer_2", sa.String(length=64), nullable=True),
        sa.Column("answer_3", sa.String(length=64), nullable=True),
        sa.Column("answer_4", sa.String(length=64), nullable=True),
        sa.Column("correct_answer", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("question_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    # ### end Alembic commands ###
