"""questions table

Revision ID: 337d787f752a
Revises: 53c2a927ac13
Create Date: 2021-04-30 11:47:17.116119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "337d787f752a"
down_revision = "53c2a927ac13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.String(length=256), nullable=True),
        sa.Column("answer_1", sa.String(length=64), nullable=True),
        sa.Column("answer_2", sa.String(length=64), nullable=True),
        sa.Column("answer_3", sa.String(length=64), nullable=True),
        sa.Column("answer_4", sa.String(length=64), nullable=True),
        sa.Column("correct_answer", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("question_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    # ### end Alembic commands ###
