"""foreign keys

Revision ID: c397a5d139df
Revises: 66c475f8a690
Create Date: 2021-04-30 12:13:50.873685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c397a5d139df"
down_revision = "66c475f8a690"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attempt", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "questions", ["question_2_id"], ["question_id"])
        batch_op.create_foreign_key(None, "questions", ["question_4_id"], ["question_id"])
        batch_op.create_foreign_key(None, "questions", ["question_5_id"], ["question_id"])
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])
        batch_op.create_foreign_key(None, "questions", ["question_1_id"], ["question_id"])
        batch_op.create_foreign_key(None, "questions", ["question_3_id"], ["question_id"])

    with op.batch_alter_table("progress", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("progress", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("attempt", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")

    # ### end Alembic commands ###
