"""empty message

Revision ID: eb45c62ff4af
Revises:
Create Date: 2021-04-28 13:57:32.220383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb45c62ff4af"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("question_1", sa.Boolean(), nullable=True),
        sa.Column("question_2", sa.Boolean(), nullable=True),
        sa.Column("question_3", sa.Boolean(), nullable=True),
        sa.Column("question_4", sa.Boolean(), nullable=True),
        sa.Column("question_5", sa.Boolean(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attempt_user_id"), "attempt", ["user_id"], unique=False)
    op.create_table(
        "learn_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("high_a", sa.Boolean(), nullable=True),
        sa.Column("high_b", sa.Boolean(), nullable=True),
        sa.Column("high_c", sa.Boolean(), nullable=True),
        sa.Column("high_d", sa.Boolean(), nullable=True),
        sa.Column("low_a", sa.Boolean(), nullable=True),
        sa.Column("low_b", sa.Boolean(), nullable=True),
        sa.Column("low_c", sa.Boolean(), nullable=True),
        sa.Column("low_d", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "questions",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.String(length=256), nullable=True),
        sa.Column("answer_1", sa.String(length=64), nullable=True),
        sa.Column("answer_2", sa.String(length=64), nullable=True),
        sa.Column("answer_3", sa.String(length=64), nullable=True),
        sa.Column("answer_4", sa.String(length=64), nullable=True),
        sa.Column("correct_answer", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("question_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_admin"), "users", ["is_admin"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_is_admin"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("questions")
    op.drop_table("learn_progress")
    op.drop_index(op.f("ix_attempt_user_id"), table_name="attempt")
    op.drop_table("attempt")
    # ### end Alembic commands ###
