"""attempt table

Revision ID: f01c5f00e589
Revises: cda076222922
Create Date: 2021-04-26 18:44:49.368995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f01c5f00e589"
down_revision = "cda076222922"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attempt", sa.Column("category", sa.String(length=64), nullable=True))
    op.drop_column("attempt", "bracket")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attempt", sa.Column("bracket", sa.VARCHAR(length=64), nullable=True))
    op.drop_column("attempt", "category")
    # ### end Alembic commands ###
