"""attempt table

Revision ID: f7239214b8d6
Revises: 7d5517a7151a
Create Date: 2021-04-19 16:30:46.495402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7239214b8d6"
down_revision = "7d5517a7151a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attempt", sa.Column("question_1_ans", sa.String(length=64), nullable=True))
    op.add_column("attempt", sa.Column("question_1_score", sa.Boolean(), nullable=True))
    op.add_column("attempt", sa.Column("question_2_ans", sa.String(length=64), nullable=True))
    op.add_column("attempt", sa.Column("question_2_score", sa.Boolean(), nullable=True))
    op.add_column("attempt", sa.Column("question_3_ans", sa.String(length=64), nullable=True))
    op.add_column("attempt", sa.Column("question_3_score", sa.Boolean(), nullable=True))
    op.add_column("attempt", sa.Column("question_4_ans", sa.String(length=64), nullable=True))
    op.add_column("attempt", sa.Column("question_4_score", sa.Boolean(), nullable=True))
    op.add_column("attempt", sa.Column("question_5_ans", sa.String(length=64), nullable=True))
    op.add_column("attempt", sa.Column("question_5_score", sa.Boolean(), nullable=True))
    op.drop_index("ix_attempt_question_1", table_name="attempt")
    op.drop_index("ix_attempt_question_2", table_name="attempt")
    op.drop_index("ix_attempt_question_3", table_name="attempt")
    op.drop_index("ix_attempt_question_4", table_name="attempt")
    op.drop_index("ix_attempt_question_5", table_name="attempt")
    op.create_index(op.f("ix_attempt_question_1_ans"), "attempt", ["question_1_ans"], unique=False)
    op.create_index(
        op.f("ix_attempt_question_1_score"), "attempt", ["question_1_score"], unique=False
    )
    op.create_index(op.f("ix_attempt_question_2_ans"), "attempt", ["question_2_ans"], unique=False)
    op.create_index(
        op.f("ix_attempt_question_2_score"), "attempt", ["question_2_score"], unique=False
    )
    op.create_index(op.f("ix_attempt_question_3_ans"), "attempt", ["question_3_ans"], unique=False)
    op.create_index(
        op.f("ix_attempt_question_3_score"), "attempt", ["question_3_score"], unique=False
    )
    op.create_index(op.f("ix_attempt_question_4_ans"), "attempt", ["question_4_ans"], unique=False)
    op.create_index(
        op.f("ix_attempt_question_4_score"), "attempt", ["question_4_score"], unique=False
    )
    op.create_index(op.f("ix_attempt_question_5_ans"), "attempt", ["question_5_ans"], unique=False)
    op.create_index(
        op.f("ix_attempt_question_5_score"), "attempt", ["question_5_score"], unique=False
    )
    op.drop_column("attempt", "question_5")
    op.drop_column("attempt", "question_1")
    op.drop_column("attempt", "question_2")
    op.drop_column("attempt", "question_3")
    op.drop_column("attempt", "question_4")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attempt", sa.Column("question_4", sa.BOOLEAN(), nullable=True))
    op.add_column("attempt", sa.Column("question_3", sa.BOOLEAN(), nullable=True))
    op.add_column("attempt", sa.Column("question_2", sa.BOOLEAN(), nullable=True))
    op.add_column("attempt", sa.Column("question_1", sa.BOOLEAN(), nullable=True))
    op.add_column("attempt", sa.Column("question_5", sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f("ix_attempt_question_5_score"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_question_5_ans"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_question_4_score"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_question_4_ans"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_question_3_score"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_question_3_ans"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_question_2_score"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_question_2_ans"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_question_1_score"), table_name="attempt")
    op.drop_index(op.f("ix_attempt_question_1_ans"), table_name="attempt")
    op.create_index("ix_attempt_question_5", "attempt", ["question_5"], unique=False)
    op.create_index("ix_attempt_question_4", "attempt", ["question_4"], unique=False)
    op.create_index("ix_attempt_question_3", "attempt", ["question_3"], unique=False)
    op.create_index("ix_attempt_question_2", "attempt", ["question_2"], unique=False)
    op.create_index("ix_attempt_question_1", "attempt", ["question_1"], unique=False)
    op.drop_column("attempt", "question_5_score")
    op.drop_column("attempt", "question_5_ans")
    op.drop_column("attempt", "question_4_score")
    op.drop_column("attempt", "question_4_ans")
    op.drop_column("attempt", "question_3_score")
    op.drop_column("attempt", "question_3_ans")
    op.drop_column("attempt", "question_2_score")
    op.drop_column("attempt", "question_2_ans")
    op.drop_column("attempt", "question_1_score")
    op.drop_column("attempt", "question_1_ans")
    # ### end Alembic commands ###
